"""Added DateTime.

Revision ID: b7aafc469ff3
Revises: 691ad2c730d1
Create Date: 2021-08-31 14:48:49.311912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7aafc469ff3'
down_revision = '691ad2c730d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_date')
    # ### end Alembic commands ###
