"""Added Currency Table

Revision ID: fe54b556c38a
Revises: b7aafc469ff3
Create Date: 2021-09-08 17:04:40.858026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe54b556c38a'
down_revision = 'b7aafc469ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_type', sa.String(), nullable=False),
    sa.Column('currency_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('currency', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email', 'account_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'currency')
    op.drop_table('currencies')
    # ### end Alembic commands ###
